# Generated by Django 3.0.5 on 2020-04-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_country_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='sender',
            new_name='country',
        ),
    ]
